version: '3.8'
services:
 pgdatabase:
   image: postgres:13.11
   environment:
     - POSTGRES_USER=rafael
     - POSTGRES_PASSWORD=rafael
     - POSTGRES_DB=produtodb
   volumes:
     - ./db:/var/lib/postgresql/data:rw"
   ports:
     - "5432:5432"
